name: Build

on:
  push:
    branches:
    - dev
    paths-ignore:
    - '**.md'
    - '**.py'

jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - name: Checkout aoe2-ai-module
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      
      - name: Restore (cache) vcpkg
        id: cache-vcpkg
        uses: actions/cache@0781355a23dac32fd3bac414512f4b903437991a
        with:
          path: |
            .\vcpkg
            !.\vcpkg\buildtrees
            !.\vcpkg\downloads
            !.\vcpkg\packages
          key: cache-vcpkg-4a678aa329c0a6323d7334fdf3ad37d571600d27-${{ hashFiles('.\aimodule\vcpkg_dependencies.txt') }}
      
      - name: Checkout vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          repository: microsoft/vcpkg
          ref: 4a678aa329c0a6323d7334fdf3ad37d571600d27
          path: vcpkg
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@c26a08ba26249b81327e26f6ef381897b6a8754d
      
      - name: Bootstrap vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: '.\vcpkg\bootstrap-vcpkg.bat'
        shell: cmd
      
      - name: Install dependencies with vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: '.\vcpkg\vcpkg install --recurse @.\aimodule\vcpkg_dependencies.txt --clean-after-build'
        shell: cmd
      
      - name: Integrate vcpkg
        run: '.\vcpkg\vcpkg integrate install'
        shell: cmd
      
      - name: Generate protobuf+grpc include files
        run: '.\protos\make-protos.bat'
        shell: cmd
      
      - name: Build AI Module x86
        run: 'msbuild .\aimodule\aimodule.vcxproj /p:Configuration=Release /p:Platform=x86'
      
      
      
      