name: Build

on:
  push:
    branches:
    - dev
    paths-ignore:
    - '**.md'
    - '**.py'

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout aoe2-ai-module
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@477b7bf94ee06669a6f06f5867061c69fbf22136
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 66bac12e4e54cc858bdf7f93c5786010b6812b13
          vcpkgArguments: '@${{ env.VCPKG_RESPONSE_FILE }}'
          appendedCacheKey: ${{ hashFiles(env.VCPKG_RESPONSE_FILE) }}
        env:
          VCPKG_RESPONSE_FILE: ${{ github.workspace }}\aimodule\vcpkg_dependencies.txt
