name: Build Documentation

on:
  push:
    branches:
    - main
    - dev
    paths:
    - 'protos/**.proto'

jobs:
  build-documentation:
    runs-on: windows-2019
    
    steps:
      - name: Checkout aoe2-ai-module
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      
      - name: Checkout ${{ github.repository }}.wiki
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          repository: ${{ github.repository }}.wiki
          path: documentation
      
      - name: Checkout protoc-gen-doc
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          repository: pseudomuto/protoc-gen-doc
          ref: f06de7ac0ef41acabeac9ac02f6f30ef15f6405f
          path: protoc-gen-doc
      
      - name: Compile protoc-gen-doc
        run: 'cd protoc-gen-doc && go build ./cmd/... & cd ..'
        shell: cmd
      
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@fc243fce3040cd0f085c9704118f849ebacbe9d3
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 8fe1851e1eb51a971b2b7cfdb8161ac03bbbd6d5
          vcpkgArguments: '@${{ env.VCPKG_RESPONSE_FILE }}'
          vcpkgTriplet: 'x64-windows-static'
          appendedCacheKey: ${{ hashFiles(env.VCPKG_RESPONSE_FILE) }}
        env:
          VCPKG_RESPONSE_FILE: ${{ github.workspace }}\aimodule\vcpkg_dependencies.txt
      
      - name: Generate protobuf documentation
        run: |
          IF %GITHUB_REF:~-3%==dev (SET WIKI_PREFIX=Dev-Branch-Documentation#)
          IF %GITHUB_REF:~-4%==main (SET WIKI_PREFIX=Documentation#)
          
          IF DEFINED WIKI_PREFIX (
            %VCPKG_ROOT%\installed\x64-windows-static\tools\protobuf\protoc.exe -I %GITHUB_WORKSPACE% -I %VCPKG_ROOT%\installed\x64-windows-static\include --doc_out %GITHUB_WORKSPACE%\documentation\ --plugin=protoc-gen-doc=%GITHUB_WORKSPACE%\protoc-gen-doc\protoc-gen-doc.exe --doc_opt=markdown,%WIKI_PREFIX%-AI-Module-API.md protos/ai_module_api.proto
            %VCPKG_ROOT%\installed\x64-windows-static\tools\protobuf\protoc.exe -I %GITHUB_WORKSPACE% -I %VCPKG_ROOT%\installed\x64-windows-static\include --doc_out %GITHUB_WORKSPACE%\documentation\ --plugin=protoc-gen-doc=%GITHUB_WORKSPACE%\protoc-gen-doc\protoc-gen-doc.exe --doc_opt=markdown,%WIKI_PREFIX%-Expert-API.md protos/expert/expert_api.proto
            %VCPKG_ROOT%\installed\x64-windows-static\tools\protobuf\protoc.exe -I %GITHUB_WORKSPACE% -I %VCPKG_ROOT%\installed\x64-windows-static\include --doc_out %GITHUB_WORKSPACE%\documentation\ --plugin=protoc-gen-doc=%GITHUB_WORKSPACE%\protoc-gen-doc\protoc-gen-doc.exe --doc_opt=markdown,%WIKI_PREFIX%-Expert-Actions.md protos/expert/action/action.proto
            %VCPKG_ROOT%\installed\x64-windows-static\tools\protobuf\protoc.exe -I %GITHUB_WORKSPACE% -I %VCPKG_ROOT%\installed\x64-windows-static\include --doc_out %GITHUB_WORKSPACE%\documentation\ --plugin=protoc-gen-doc=%GITHUB_WORKSPACE%\protoc-gen-doc\protoc-gen-doc.exe --doc_opt=markdown,%WIKI_PREFIX%-Expert-Facts.md protos/expert/fact/fact.proto
          )
        shell: cmd
      
      - name: Commit and push wiki files
        run: |
          cd documentation
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Add changes" && git push
          cd ..
        shell: cmd
      