# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run.
on:
  push:
    branches:
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-2019
    env:
      PreferredToolArchitecture: x64
      VCPKG_RESPONSE_FILE: ${{ github.workspace }}/aimodule/vcpkg_dependencies.txt

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the branch of this repository from where this workflow was called from under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command
      - name: Run a one-line script
        run: echo Hello, world! %VCPKG_RESPONSE_FILE% %PreferredToolArchitecture%
        shell: cmd
